name: Post release topic on Discourse

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
    - uses: roots/discourse-topic-github-release-action@main
      with:
        discourse-api-key: ${{ secrets.DISCOURSE_RELEASES_API_KEY }}
        discourse-base-url: ${{ secrets.DISCOURSE_BASE_URL }}
        discourse-author-username: system
        discourse-category: 7
        discourse-tags:
          releases
